const API_BASE_URL_DEVELOPMENT = "https://localhost:7218";
const API_BASE_URL_PRODUCTION = "https://appname.azurewebsites.net";

const ENDPOINTS = {
  GET_ALL_STAFFS: "get-all-staffs",
  GET_STAFF_BY_ID: "get-staff-by-id",
  CREATE_STAFF: "create-staff",
  UPDATE_STAFF: "update-staff",
  DELETE_STAFF_BY_ID: "delete-staff-by-id",
};

const development = {
  API_URL_GET_ALL_STAFFS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_STAFFS}`,
  API_URL_GET_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_STAFF_BY_ID}`,
  API_URL_CREATE_STAFF: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_STAFF}`,
  API_URL_UPDATE_STAFF: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_STAFF}`,
  API_URL_DELETE_STAFF_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_STAFF_BY_ID}`,
};

const production = {
  API_URL_GET_ALL_STAFFS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_STAFFS}`,
  API_URL_GET_USER_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_STAFF_BY_ID}`,
  API_URL_CREATE_STAFF: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_STAFF}`,
  API_URL_UPDATE_STAFF: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_STAFF}`,
  API_URL_DELETE_USER_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_STAFF_BY_ID}`,
};

const Constants =
  process.env.NODE_ENV === `development` ? development : production;

export default Constants;
