// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace clockingapi.Data.Migrations
{
    [DbContext(typeof(clockingdbcontext))]
    [Migration("20220228135141_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Regnumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "The User's 1 FirstName is ",
                            LastName = "The User's 1 LastName is  ",
                            Regnumber = "The User's 1 RegNumber is ",
                            Role = "The User's 1 Role is "
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "The User's 2 FirstName is ",
                            LastName = "The User's 2 LastName is  ",
                            Regnumber = "The User's 2 RegNumber is ",
                            Role = "The User's 2 Role is "
                        },
                        new
                        {
                            UserId = 3,
                            FirstName = "The User's 3 FirstName is ",
                            LastName = "The User's 3 LastName is  ",
                            Regnumber = "The User's 3 RegNumber is ",
                            Role = "The User's 3 Role is "
                        },
                        new
                        {
                            UserId = 4,
                            FirstName = "The User's 4 FirstName is ",
                            LastName = "The User's 4 LastName is  ",
                            Regnumber = "The User's 4 RegNumber is ",
                            Role = "The User's 4 Role is "
                        },
                        new
                        {
                            UserId = 5,
                            FirstName = "The User's 5 FirstName is ",
                            LastName = "The User's 5 LastName is  ",
                            Regnumber = "The User's 5 RegNumber is ",
                            Role = "The User's 5 Role is "
                        },
                        new
                        {
                            UserId = 6,
                            FirstName = "The User's 6 FirstName is ",
                            LastName = "The User's 6 LastName is  ",
                            Regnumber = "The User's 6 RegNumber is ",
                            Role = "The User's 6 Role is "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
